<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('url');
        $this->load->model('login_model');
        $this->load->model('orangtua_model');
        $this->load->model('guru_model');
        $this->load->model('siswa_model');
    }

    public function index()
    {
        if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
        {
            redirect('dashboard');
        }

        if(!$this->input->post())
        {
            $this->load->view('login/login');
        }
        else
        {
            $data = $this->login_model->cek_login(
                $this->input->post('username'),
                $this->input->post('password')
            );
            if(!empty($data) && $data->role_id != 5)
            {
                $this->session->set_userdata('logined', true);
                $this->session->set_userdata('username', $data->username);
                $this->session->set_userdata('role_id', $data->role_id);
                $this->session->set_userdata('user_id', $data->user_id);
                redirect("dashboard");
            }
            else
            {
                redirect("");
            }
        }

    }

    public function logout()
    {
        session_destroy();
        $this->session->unset_userdata('logined');
        redirect("login");
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */