<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('url');
        $this->load->model('user_model');
    }

    public function index()
    {
        if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
        {
            redirect('dashboard');
        }

        if(!$this->input->post())
        {
            $this->load->view('login/login');
        }
        else
        {
            $data = $this->user_model->cek_login(
                $this->input->post('username'),
                $this->input->post('password')
            );
            if(!empty($data) && $data->role_id != 5)
            {
                $this->session->set_userdata('logined', true);
                $this->session->set_userdata('username', $data->username);
                $this->session->set_userdata('role_id', $data->role_id);
                $this->session->set_userdata('user_id', $data->id);
                redirect("dashboard");
            }
            else
            {
                redirect("");
            }
        }

    }

    public function logout()
    {
        session_destroy();
        $this->session->unset_userdata('logined');
        redirect("login");
    }

    public function editPassword()
    {
        $data['user'] = $this->user_model->getById($this->session->userdata('user_id'));
        $this->load->view('login/edit_password', $data);
    }

    public function updatePassword($id)
    {
        $data = array(
            'password' => $this->input->post('password')
        );
        $this->user_model->update($id, $data);
        redirect('dashboard');
    }

}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */